name: CI
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        node: ['14', '16', '18']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node }}'
          cache: npm
      - run: npm install
      - run: npm test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: npm
      - run: npm install
      - run: npm run lint
